PLANS_SEED = [
    {
        "code": "BASIC",
        "name": "Basic",
        "description": "Perfect for single-location businesses just getting started.",
        "price_monthly": 1490.00,
        "price_yearly": 14300.00,  # billed annually (~20% off)
        "currency": "KES",
        "is_active": True,
        "is_public": True,
        "trial_days": 7,
        "sort_order": 1,
        "limits": {
            "max_businesses": 1,
            "max_staff": 3,
            "max_products": 300,
            "max_customers": 200,
            "max_transactions_per_month": 1000,
            "max_invoices_per_month": 500,
            "data_retention_months": 6,
        },
        "features": {
            "pos_and_sales": True,
            "invoicing": True,
            "basic_stock_tracking": True,
            "full_inventory": False,
            "low_stock_alerts": False,
            "customer_management": True,
            "customer_credit": False,
            "expense_tracking": False,
            "multi_business": False,
            "receipt_customization": False,
            "daily_sales_report": True,
            "advanced_reports": False,
            "profit_and_loss": False,
            "staff_performance": False,
            "custom_reports": False,
            "pin_login": True,
            "audit_trail": False,
            "api_access": False,
            "sso": False,
            "enhanced_security": False,
            "email_support": True,
            "whatsapp_support": False,
            "phone_support": False,
            "priority_support": False,
            "dedicated_account_manager": False,
            "onboarding_training": False,
            "automatic_backups": False,
            "offline_mode": False,
            "supplier_management": False,
            "purchase_orders": False,
            "batch_tracking": False,
            "custom_domain": False,
            "white_label": False,
            "csv_export": True,
            "pdf_export": False,
        },
    },
    {
        "code": "NDOVU",
        "name": "Ndovu",
        "description": "The recommended plan for growing businesses. Strength, memory, and reliability.",
        "price_monthly": 2499.00,
        "price_yearly": 29988.00,  # billed annually (~20% off)
        "currency": "KES",
        "is_active": True,
        "is_public": True,
        "trial_days": 7,
        "sort_order": 2,
        "limits": {
            "max_businesses": 5,
            "max_staff": 25,
            "max_products": 5000,
            "max_customers": 5000,
            "max_transactions_per_month": 15000,
            "max_invoices_per_month": 8000,
            "data_retention_months": 12,
        },
        "features": {
            "pos_and_sales": True,
            "invoicing": True,
            "basic_stock_tracking": True,
            "full_inventory": True,
            "low_stock_alerts": True,
            "customer_management": True,
            "customer_credit": True,
            "expense_tracking": True,
            "multi_business": True,
            "receipt_customization": True,
            "daily_sales_report": True,
            "advanced_reports": True,
            "profit_and_loss": True,
            "staff_performance": True,
            "custom_reports": False,
            "pin_login": True,
            "audit_trail": "basic",
            "api_access": "limited",  # 1 key · 2,000 req/day (paywall)
            "sso": False,
            "enhanced_security": False,
            "email_support": True,
            "whatsapp_support": True,
            "phone_support": False,
            "priority_support": True,
            "dedicated_account_manager": False,
            "onboarding_training": False,
            "automatic_backups": True,
            "offline_mode": "limited",
            "supplier_management": False,
            "purchase_orders": False,
            "batch_tracking": False,
            "custom_domain": False,
            "white_label": True,  # branding from Ndovu
            "csv_export": True,
            "pdf_export": True,
        },
    },
    {
        "code": "ENTERPRISE",
        "name": "Enterprise",
        "description": "For complex multi-branch operations that need full control, compliance, and scale.",
        "price_monthly": 8990.00,
        "price_yearly": None,  # custom / sales-led
        "currency": "KES",
        "is_active": True,
        "is_public": True,
        "trial_days": 14,
        "sort_order": 3,
        "limits": {
            "max_businesses": 20,
            "max_staff": 100,
            "max_products": 25000,
            "max_customers": 25000,
            "max_transactions_per_month": 75000,
            "max_invoices_per_month": 40000,
            "data_retention_months": 36,
        },
        "features": {
            "pos_and_sales": True,
            "invoicing": True,
            "basic_stock_tracking": True,
            "full_inventory": True,
            "low_stock_alerts": True,
            "customer_management": True,
            "customer_credit": True,
            "expense_tracking": True,
            "multi_business": True,
            "receipt_customization": True,
            "daily_sales_report": True,
            "advanced_reports": True,
            "profit_and_loss": True,
            "staff_performance": True,
            "custom_reports": True,
            "pin_login": True,
            "audit_trail": "full",
            "api_access": "standard",  # 5 keys · 20,000 req/day (paywall)
            "sso": True,
            "enhanced_security": True,
            "email_support": True,
            "whatsapp_support": True,
            "phone_support": True,
            "priority_support": True,
            "dedicated_account_manager": True,
            "onboarding_training": True,
            "automatic_backups": True,
            "offline_mode": "full",
            "supplier_management": True,
            "purchase_orders": True,
            "batch_tracking": True,
            "custom_domain": True,
            "white_label": True,
            "csv_export": True,
            "pdf_export": True,
        },
    },
]
