"""adds, staff, subscriptions and many more models

Revision ID: 08aa8478a0e5
Revises: f7aa1cafd538
Create Date: 2026-05-23 22:41:36.518691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08aa8478a0e5'
down_revision: Union[str, Sequence[str], None] = 'f7aa1cafd538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'CASHIER', 'KITCHEN_STAFF', name='staff_role_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_active'), 'staff', ['active'], unique=False)
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_tenant_id'), 'staff', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'BRONZE', 'SILVER', 'GOLD', name='subscription_tier_enum'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('max_registers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_active'), 'subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_subscriptions_end_date'), 'subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    op.create_table('sale_analytics_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('date_dimension', sa.DateTime(), nullable=False),
    sa.Column('gross_sales_volume', sa.Float(), nullable=False),
    sa.Column('total_tax_collected', sa.Float(), nullable=False),
    sa.Column('total_discounts_granted', sa.Float(), nullable=False),
    sa.Column('net_revenue_collected', sa.Float(), nullable=False),
    sa.Column('refund_deductions_volume', sa.Float(), nullable=False),
    sa.Column('total_completed_orders_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_analytics_summaries_business_id'), 'sale_analytics_summaries', ['business_id'], unique=False)
    op.create_index(op.f('ix_sale_analytics_summaries_date_dimension'), 'sale_analytics_summaries', ['date_dimension'], unique=False)
    op.create_index(op.f('ix_sale_analytics_summaries_id'), 'sale_analytics_summaries', ['id'], unique=False)
    op.create_table('staff_business_assignments',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'business_id')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_refunded', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sku'), 'sale_items', ['sku'], unique=False)
    op.create_table('sale_ledger_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('INITIAL_SALE', 'INVOICE_ISSUED', 'PAYMENT_COLLECTED', 'ITEM_RETURNED', 'DISPUTE_RAISED', name='event_type_enum'), nullable=True),
    sa.Column('amount_delta', sa.Float(), nullable=False),
    sa.Column('product_id_context', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_ledger_events_id'), 'sale_ledger_events', ['id'], unique=False)
    op.create_index(op.f('ix_sale_ledger_events_product_id_context'), 'sale_ledger_events', ['product_id_context'], unique=False)
    op.create_index(op.f('ix_sale_ledger_events_sale_id'), 'sale_ledger_events', ['sale_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.alter_column('products', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'track_stock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('sales', sa.Column('cashier_id', sa.Uuid(), nullable=False))
    op.add_column('sales', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False))
    op.add_column('sales', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('tax_rate', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('tax_amount', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('discount_applied', sa.Float(), nullable=False))
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_sales_cashier_id'), 'sales', ['cashier_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'staff', ['cashier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_cashier_id'), table_name='sales')
    op.alter_column('sales', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('sales', 'discount_applied')
    op.drop_column('sales', 'tax_amount')
    op.drop_column('sales', 'tax_rate')
    op.drop_column('sales', 'subtotal')
    op.drop_column('sales', 'currency')
    op.drop_column('sales', 'cashier_id')
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'track_stock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_sale_ledger_events_sale_id'), table_name='sale_ledger_events')
    op.drop_index(op.f('ix_sale_ledger_events_product_id_context'), table_name='sale_ledger_events')
    op.drop_index(op.f('ix_sale_ledger_events_id'), table_name='sale_ledger_events')
    op.drop_table('sale_ledger_events')
    op.drop_index(op.f('ix_sale_items_sku'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_table('staff_business_assignments')
    op.drop_index(op.f('ix_sale_analytics_summaries_id'), table_name='sale_analytics_summaries')
    op.drop_index(op.f('ix_sale_analytics_summaries_date_dimension'), table_name='sale_analytics_summaries')
    op.drop_index(op.f('ix_sale_analytics_summaries_business_id'), table_name='sale_analytics_summaries')
    op.drop_table('sale_analytics_summaries')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_end_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_active'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_staff_tenant_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_index(op.f('ix_staff_active'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
