""" fixes config does exist on business

Revision ID: 08c06f619b34
Revises: 1fd246af1683
Create Date: 2026-08-07 02:34:47.049796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08c06f619b34'
down_revision: Union[str, Sequence[str], None] = '1fd246af1683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('businesses', 'settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'config')
    # ### end Alembic commands ###
