"""hotfix

Revision ID: 166eb1e39b20
Revises: 18537afe6b0a
Create Date: 2026-07-15 02:06:39.450051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '166eb1e39b20'
down_revision: Union[str, Sequence[str], None] = '18537afe6b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_business_analytics_date', 'sale_analytics_summaries', ['business_id', 'date_dimension'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_analytics_date', 'sale_analytics_summaries', type_='unique')
    # ### end Alembic commands ###
