"""adds a permanent snapshop of a receipt

Revision ID: 18537afe6b0a
Revises: c7da504022e6
Create Date: 2026-07-14 18:35:11.523708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18537afe6b0a'
down_revision: Union[str, Sequence[str], None] = 'c7da504022e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_documents', sa.Column('document_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('products', 'popularity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'popularity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('financial_documents', 'document_snapshot')
    # ### end Alembic commands ###
