"""adds stock_batch_id in the SaleItem table

Revision ID: 18cc7093f908
Revises: 0487ba4313a6
Create Date: 2026-06-03 03:35:44.433100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18cc7093f908'
down_revision: Union[str, Sequence[str], None] = '0487ba4313a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('stock_batch_id', sa.Uuid(), nullable=True))
    op.add_column('sale_items', sa.Column('cost_price_at_sale', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'sale_items', 'stock_batches', ['stock_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'cost_price_at_sale')
    op.drop_column('sale_items', 'stock_batch_id')
    # ### end Alembic commands ###
