"""adds foreign key to finanial document pointing to sales items

Revision ID: 1cce4dfdaafe
Revises: 171d4f819971
Create Date: 2026-06-23 19:11:24.173784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cce4dfdaafe'
down_revision: Union[str, Sequence[str], None] = '171d4f819971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('financial_document_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sale_items_financial_document_id'), 'sale_items', ['financial_document_id'], unique=False)
    op.create_foreign_key(None, 'sale_items', 'financial_documents', ['financial_document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_financial_document_id'), table_name='sale_items')
    op.drop_column('sale_items', 'financial_document_id')
    # ### end Alembic commands ###
