# """database make over to support compliace,billing, auditing

# Revision ID: 1cd7948300ae
# Revises: 08c06f619b34
# Create Date: 2026-08-09 00:13:16.419065

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# import sqlmodel
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = '1cd7948300ae'
# down_revision: Union[str, Sequence[str], None] = '08c06f619b34'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('audit_logs',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('organization_id', sa.Uuid(), nullable=True),
#     sa.Column('actor_id', sa.Uuid(), nullable=True),
#     sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('entity_id', sa.Uuid(), nullable=True),
#     sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
#     op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
#     op.create_index(op.f('ix_audit_logs_actor_role'), 'audit_logs', ['actor_role'], unique=False)
#     op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
#     op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
#     op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
#     op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
#     op.create_table('plans',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
#     sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
#     sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('price_monthly', sa.Float(), nullable=False),
#     sa.Column('price_yearly', sa.Float(), nullable=True),
#     sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
#     sa.Column('is_active', sa.Boolean(), nullable=False),
#     sa.Column('is_public', sa.Boolean(), nullable=False),
#     sa.Column('trial_days', sa.Integer(), nullable=False),
#     sa.Column('sort_order', sa.Integer(), nullable=False),
#     sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
#     op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
#     op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
#     op.create_table('platform_users',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
#     sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('role', sa.Enum('SUPER_ADMIN', 'SUPPORT', 'BILLING', 'AUDITOR', name='platform_role_enum'), nullable=True),
#     sa.Column('active', sa.Boolean(), nullable=False),
#     sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_platform_users_active'), 'platform_users', ['active'], unique=False)
#     op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
#     op.create_index(op.f('ix_platform_users_id'), 'platform_users', ['id'], unique=False)
#     op.create_table('data_deletion_requests',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('organization_id', sa.Uuid(), nullable=True),
#     sa.Column('requested_by_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
#     sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_data_deletion_requests_id'), 'data_deletion_requests', ['id'], unique=False)
#     op.create_index(op.f('ix_data_deletion_requests_organization_id'), 'data_deletion_requests', ['organization_id'], unique=False)
#     op.create_index(op.f('ix_data_deletion_requests_status'), 'data_deletion_requests', ['status'], unique=False)
#     op.create_table('categories',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('organization_id', sa.Uuid(), nullable=True),
#     sa.Column('business_id', sa.Uuid(), nullable=True),
#     sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
#     sa.Column('parent_id', sa.Uuid(), nullable=True),
#     sa.Column('sort_order', sa.Integer(), nullable=False),
#     sa.Column('active', sa.Boolean(), nullable=False),
#     sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_categories_active'), 'categories', ['active'], unique=False)
#     op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
#     op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
#     op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
#     op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
#     op.add_column('businesses', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_businesses_deleted_by'), 'businesses', ['deleted_by'], unique=False)
#     op.add_column('customers', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_customers_deleted_by'), 'customers', ['deleted_by'], unique=False)
#     op.add_column('organizations', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_organizations_deleted_by'), 'organizations', ['deleted_by'], unique=False)
#     op.add_column('products', sa.Column('item_type', sa.Enum('PRODUCT', 'SERVICE', name='item_type_enum'), nullable=True))
#     op.add_column('products', sa.Column('category_id', sa.Uuid(), nullable=True))
#     op.add_column('products', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
#     op.create_index(op.f('ix_products_deleted_by'), 'products', ['deleted_by'], unique=False)
#     op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
#     op.add_column('staff', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_staff_deleted_by'), 'staff', ['deleted_by'], unique=False)
#     op.add_column('subscriptions', sa.Column('plan_id', sa.Uuid(), nullable=True))
#     op.add_column('subscriptions', sa.Column('current_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
#     op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
#     op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'subscriptions', type_='foreignkey')
#     op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
#     op.drop_column('subscriptions', 'current_usage')
#     op.drop_column('subscriptions', 'plan_id')
#     op.drop_index(op.f('ix_staff_deleted_by'), table_name='staff')
#     op.drop_column('staff', 'deleted_by')
#     op.drop_constraint(None, 'products', type_='foreignkey')
#     op.drop_index(op.f('ix_products_deleted_by'), table_name='products')
#     op.drop_index(op.f('ix_products_category_id'), table_name='products')
#     op.drop_column('products', 'deleted_by')
#     op.drop_column('products', 'category_id')
#     op.drop_column('products', 'item_type')
#     op.drop_index(op.f('ix_organizations_deleted_by'), table_name='organizations')
#     op.drop_column('organizations', 'deleted_by')
#     op.drop_index(op.f('ix_customers_deleted_by'), table_name='customers')
#     op.drop_column('customers', 'deleted_by')
#     op.drop_index(op.f('ix_businesses_deleted_by'), table_name='businesses')
#     op.drop_column('businesses', 'deleted_by')
#     op.drop_index(op.f('ix_categories_organization_id'), table_name='categories')
#     op.drop_index(op.f('ix_categories_name'), table_name='categories')
#     op.drop_index(op.f('ix_categories_id'), table_name='categories')
#     op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
#     op.drop_index(op.f('ix_categories_active'), table_name='categories')
#     op.drop_table('categories')
#     op.drop_index(op.f('ix_data_deletion_requests_status'), table_name='data_deletion_requests')
#     op.drop_index(op.f('ix_data_deletion_requests_organization_id'), table_name='data_deletion_requests')
#     op.drop_index(op.f('ix_data_deletion_requests_id'), table_name='data_deletion_requests')
#     op.drop_table('data_deletion_requests')
#     op.drop_index(op.f('ix_platform_users_id'), table_name='platform_users')
#     op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
#     op.drop_index(op.f('ix_platform_users_active'), table_name='platform_users')
#     op.drop_table('platform_users')
#     op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
#     op.drop_index(op.f('ix_plans_id'), table_name='plans')
#     op.drop_index(op.f('ix_plans_code'), table_name='plans')
#     op.drop_table('plans')
#     op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_actor_role'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
#     op.drop_table('audit_logs')
#     # ### end Alembic commands ###


# """database make over to support compliace,billing, auditing

# Revision ID: 1cd7948300ae
# Revises: 08c06f619b34
# Create Date: 2026-08-09 00:13:16.419065

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# import sqlmodel
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = '1cd7948300ae'
# down_revision: Union[str, Sequence[str], None] = '08c06f619b34'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""

#     # -------------------------------------------------
#     # CRITICAL: Create PostgreSQL ENUM types FIRST
#     # Alembic does not reliably auto-create them when used in add_column()
#     # -------------------------------------------------
#     # Robust ENUM creation (avoids both "does not exist" and "already exists")
#     # -------------------------------------------------
#     item_type_enum = sa.Enum('PRODUCT', 'SERVICE', name='item_type_enum', create_type=False)
#     platform_role_enum = sa.Enum(
#         'SUPER_ADMIN', 'SUPPORT', 'BILLING', 'AUDITOR',
#         name='platform_role_enum',
#         create_type=False
#     )

#     # Explicitly create them once
#     item_type_enum.create(op.get_bind(), checkfirst=True)
#     platform_role_enum.create(op.get_bind(), checkfirst=True)

#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('audit_logs',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('organization_id', sa.Uuid(), nullable=True),
#     sa.Column('actor_id', sa.Uuid(), nullable=True),
#     sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('entity_id', sa.Uuid(), nullable=True),
#     sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
#     op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
#     op.create_index(op.f('ix_audit_logs_actor_role'), 'audit_logs', ['actor_role'], unique=False)
#     op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
#     op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
#     op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
#     op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)

#     op.create_table('plans',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
#     sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
#     sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('price_monthly', sa.Float(), nullable=False),
#     sa.Column('price_yearly', sa.Float(), nullable=True),
#     sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
#     sa.Column('is_active', sa.Boolean(), nullable=False),
#     sa.Column('is_public', sa.Boolean(), nullable=False),
#     sa.Column('trial_days', sa.Integer(), nullable=False),
#     sa.Column('sort_order', sa.Integer(), nullable=False),
#     sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
#     op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
#     op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)

#     op.create_table('platform_users',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
#     sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('role', platform_role_enum, nullable=True),  # ← use the already-created enum
#     sa.Column('active', sa.Boolean(), nullable=False),
#     sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_platform_users_active'), 'platform_users', ['active'], unique=False)
#     op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
#     op.create_index(op.f('ix_platform_users_id'), 'platform_users', ['id'], unique=False)

#     op.create_table('data_deletion_requests',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('organization_id', sa.Uuid(), nullable=True),
#     sa.Column('requested_by_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
#     sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
#     sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
#     sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
#     sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_data_deletion_requests_id'), 'data_deletion_requests', ['id'], unique=False)
#     op.create_index(op.f('ix_data_deletion_requests_organization_id'), 'data_deletion_requests', ['organization_id'], unique=False)
#     op.create_index(op.f('ix_data_deletion_requests_status'), 'data_deletion_requests', ['status'], unique=False)

#     op.create_table('categories',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('organization_id', sa.Uuid(), nullable=True),
#     sa.Column('business_id', sa.Uuid(), nullable=True),
#     sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
#     sa.Column('parent_id', sa.Uuid(), nullable=True),
#     sa.Column('sort_order', sa.Integer(), nullable=False),
#     sa.Column('active', sa.Boolean(), nullable=False),
#     sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_categories_active'), 'categories', ['active'], unique=False)
#     op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
#     op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
#     op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
#     op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)

#     op.add_column('businesses', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_businesses_deleted_by'), 'businesses', ['deleted_by'], unique=False)

#     op.add_column('customers', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_customers_deleted_by'), 'customers', ['deleted_by'], unique=False)

#     op.add_column('organizations', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_organizations_deleted_by'), 'organizations', ['deleted_by'], unique=False)

#     # Now safe – the ENUM type already exists
#     op.add_column(
#         'products',
#         sa.Column(
#             'item_type',
#             item_type_enum,
#             nullable=False,
#             server_default='PRODUCT'          # existing rows become PRODUCT
#         )
#     )
#     op.add_column('products', sa.Column('category_id', sa.Uuid(), nullable=True))
#     op.add_column('products', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
#     op.create_index(op.f('ix_products_deleted_by'), 'products', ['deleted_by'], unique=False)
#     op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])

#     op.add_column('staff', sa.Column('deleted_by', sa.Uuid(), nullable=True))
#     op.create_index(op.f('ix_staff_deleted_by'), 'staff', ['deleted_by'], unique=False)

#     op.add_column('subscriptions', sa.Column('plan_id', sa.Uuid(), nullable=True))
#     op.add_column('subscriptions', sa.Column('current_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
#     op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
#     op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'subscriptions', type_='foreignkey')
#     op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
#     op.drop_column('subscriptions', 'current_usage')
#     op.drop_column('subscriptions', 'plan_id')

#     op.drop_index(op.f('ix_staff_deleted_by'), table_name='staff')
#     op.drop_column('staff', 'deleted_by')

#     op.drop_constraint(None, 'products', type_='foreignkey')
#     op.drop_index(op.f('ix_products_deleted_by'), table_name='products')
#     op.drop_index(op.f('ix_products_category_id'), table_name='products')
#     op.drop_column('products', 'deleted_by')
#     op.drop_column('products', 'category_id')
#     op.drop_column('products', 'item_type')

#     op.drop_index(op.f('ix_organizations_deleted_by'), table_name='organizations')
#     op.drop_column('organizations', 'deleted_by')

#     op.drop_index(op.f('ix_customers_deleted_by'), table_name='customers')
#     op.drop_column('customers', 'deleted_by')

#     op.drop_index(op.f('ix_businesses_deleted_by'), table_name='businesses')
#     op.drop_column('businesses', 'deleted_by')

#     op.drop_index(op.f('ix_categories_organization_id'), table_name='categories')
#     op.drop_index(op.f('ix_categories_name'), table_name='categories')
#     op.drop_index(op.f('ix_categories_id'), table_name='categories')
#     op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
#     op.drop_index(op.f('ix_categories_active'), table_name='categories')
#     op.drop_table('categories')

#     op.drop_index(op.f('ix_data_deletion_requests_status'), table_name='data_deletion_requests')
#     op.drop_index(op.f('ix_data_deletion_requests_organization_id'), table_name='data_deletion_requests')
#     op.drop_index(op.f('ix_data_deletion_requests_id'), table_name='data_deletion_requests')
#     op.drop_table('data_deletion_requests')

#     op.drop_index(op.f('ix_platform_users_id'), table_name='platform_users')
#     op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
#     op.drop_index(op.f('ix_platform_users_active'), table_name='platform_users')
#     op.drop_table('platform_users')

#     op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
#     op.drop_index(op.f('ix_plans_id'), table_name='plans')
#     op.drop_index(op.f('ix_plans_code'), table_name='plans')
#     op.drop_table('plans')

#     op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_actor_role'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
#     op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
#     op.drop_table('audit_logs')

#     # Drop the ENUM types last
#     sa.Enum(name='item_type_enum').drop(op.get_bind(), checkfirst=True)
#     sa.Enum(name='platform_role_enum').drop(op.get_bind(), checkfirst=True)
#     # ### end Alembic commands ###


"""database make over to support compliace,billing, auditing

Revision ID: 1cd7948300ae
Revises: 08c06f619b34
Create Date: 2026-08-09 00:13:16.419065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1cd7948300ae"
down_revision: Union[str, Sequence[str], None] = "08c06f619b34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # -------------------------------------------------
    # CRITICAL: Create PostgreSQL ENUM types FIRST
    # Use raw DO-block – this is the only 100% reliable way
    # to avoid both "does not exist" and "already exists"
    # -------------------------------------------------
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_type_enum') THEN
                CREATE TYPE item_type_enum AS ENUM ('PRODUCT', 'SERVICE');
            END IF;
        END
        $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'platform_role_enum') THEN
                CREATE TYPE platform_role_enum AS ENUM (
                    'SUPER_ADMIN', 'SUPPORT', 'BILLING', 'AUDITOR'
                );
            END IF;
        END
        $$;
    """)

    # Re-create the Enum objects with create_type=False
    # so SQLAlchemy never tries to CREATE TYPE again
    item_type_enum = postgresql.ENUM(
        "PRODUCT", "SERVICE", name="item_type_enum", create_type=False
    )
    platform_role_enum = postgresql.ENUM(
        "SUPER_ADMIN",
        "SUPPORT",
        "BILLING",
        "AUDITOR",
        name="platform_role_enum",
        create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_role"), "audit_logs", ["actor_role"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_organization_id"),
        "audit_logs",
        ["organization_id"],
        unique=False,
    )

    op.create_table(
        "plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price_monthly", sa.Float(), nullable=False),
        sa.Column("price_yearly", sa.Float(), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("trial_days", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plans_code"), "plans", ["code"], unique=True)
    op.create_index(op.f("ix_plans_id"), "plans", ["id"], unique=False)
    op.create_index(op.f("ix_plans_is_active"), "plans", ["is_active"], unique=False)

    op.create_table(
        "platform_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "role", platform_role_enum, nullable=True
        ),  # ← use the already-created enum
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_users_active"), "platform_users", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_platform_users_email"), "platform_users", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_platform_users_id"), "platform_users", ["id"], unique=False
    )

    op.create_table(
        "data_deletion_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "requested_by_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "actions_taken", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_deletion_requests_id"),
        "data_deletion_requests",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_deletion_requests_organization_id"),
        "data_deletion_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_deletion_requests_status"),
        "data_deletion_requests",
        ["status"],
        unique=False,
    )

    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_active"), "categories", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_categories_business_id"), "categories", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(
        op.f("ix_categories_organization_id"),
        "categories",
        ["organization_id"],
        unique=False,
    )

    op.add_column("businesses", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_businesses_deleted_by"), "businesses", ["deleted_by"], unique=False
    )

    op.add_column("customers", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_customers_deleted_by"), "customers", ["deleted_by"], unique=False
    )

    op.add_column("organizations", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_organizations_deleted_by"),
        "organizations",
        ["deleted_by"],
        unique=False,
    )

    # Now safe – the ENUM type already exists
    op.add_column(
        "products",
        sa.Column(
            "item_type",
            item_type_enum,
            nullable=False,
            server_default="PRODUCT",  # existing rows become PRODUCT
        ),
    )
    op.add_column("products", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.add_column("products", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_deleted_by"), "products", ["deleted_by"], unique=False
    )
    op.create_foreign_key(None, "products", "categories", ["category_id"], ["id"])

    op.add_column("staff", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_staff_deleted_by"), "staff", ["deleted_by"], unique=False)

    op.add_column("subscriptions", sa.Column("plan_id", sa.Uuid(), nullable=True))
    op.add_column(
        "subscriptions",
        sa.Column(
            "current_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_subscriptions_plan_id"), "subscriptions", ["plan_id"], unique=False
    )
    op.create_foreign_key(None, "subscriptions", "plans", ["plan_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.drop_index(op.f("ix_subscriptions_plan_id"), table_name="subscriptions")
    op.drop_column("subscriptions", "current_usage")
    op.drop_column("subscriptions", "plan_id")

    op.drop_index(op.f("ix_staff_deleted_by"), table_name="staff")
    op.drop_column("staff", "deleted_by")

    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_index(op.f("ix_products_deleted_by"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_column("products", "deleted_by")
    op.drop_column("products", "category_id")
    op.drop_column("products", "item_type")

    op.drop_index(op.f("ix_organizations_deleted_by"), table_name="organizations")
    op.drop_column("organizations", "deleted_by")

    op.drop_index(op.f("ix_customers_deleted_by"), table_name="customers")
    op.drop_column("customers", "deleted_by")

    op.drop_index(op.f("ix_businesses_deleted_by"), table_name="businesses")
    op.drop_column("businesses", "deleted_by")

    op.drop_index(op.f("ix_categories_organization_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_business_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_active"), table_name="categories")
    op.drop_table("categories")

    op.drop_index(
        op.f("ix_data_deletion_requests_status"), table_name="data_deletion_requests"
    )
    op.drop_index(
        op.f("ix_data_deletion_requests_organization_id"),
        table_name="data_deletion_requests",
    )
    op.drop_index(
        op.f("ix_data_deletion_requests_id"), table_name="data_deletion_requests"
    )
    op.drop_table("data_deletion_requests")

    op.drop_index(op.f("ix_platform_users_id"), table_name="platform_users")
    op.drop_index(op.f("ix_platform_users_email"), table_name="platform_users")
    op.drop_index(op.f("ix_platform_users_active"), table_name="platform_users")
    op.drop_table("platform_users")

    op.drop_index(op.f("ix_plans_is_active"), table_name="plans")
    op.drop_index(op.f("ix_plans_id"), table_name="plans")
    op.drop_index(op.f("ix_plans_code"), table_name="plans")
    op.drop_table("plans")

    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_role"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")

    # Drop the ENUM types last (only if they exist)
    op.execute("DROP TYPE IF EXISTS item_type_enum")
    op.execute("DROP TYPE IF EXISTS platform_role_enum")
    # ### end Alembic commands ###
