"""fixed stock inventory table

Revision ID: 1f7523183204
Revises: fb80521d3103
Create Date: 2026-06-05 04:25:50.708102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7523183204'
down_revision: Union[str, Sequence[str], None] = 'fb80521d3103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_takes')
    op.alter_column('customers', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'])
    op.drop_column('customers', 'active')
    op.drop_column('customers', 'balance')
    op.drop_column('customers', 'address')
    op.add_column('inventory_transactions', sa.Column('buying_price', sa.Float(), nullable=True))
    op.alter_column('inventory_transactions', 'previous_stock',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('inventory_transactions_performed_by_fkey'), 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_transactions', 'staff', ['performed_by'], ['id'], ondelete='CASCADE')
    op.drop_column('inventory_transactions', 'batch_reference')
    op.drop_column('inventory_transactions', 'notes')
    op.drop_column('inventory_transactions', 'purchase_cost_price')
    op.add_column('sales', sa.Column('discount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount')
    op.add_column('inventory_transactions', sa.Column('purchase_cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('batch_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_transactions_performed_by_fkey'), 'inventory_transactions', 'staff', ['performed_by'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_transactions', 'previous_stock',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('inventory_transactions', 'buying_price')
    op.add_column('customers', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.alter_column('customers', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('stock_takes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'COMPLETED', 'APPROVED', 'CANCELLED', name='stock_take_status_enum'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_items_counted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('stock_takes_business_id_fkey')),
    sa.ForeignKeyConstraint(['performed_by'], ['staff.id'], name=op.f('stock_takes_performed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_takes_pkey'))
    )
    # ### end Alembic commands ###
