"""total isolation from the database level

Revision ID: 1fd246af1683
Revises: 6115e7847ece
Create Date: 2026-08-07 02:28:42.990039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fd246af1683'
down_revision: Union[str, Sequence[str], None] = '6115e7847ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'businesses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('businesses', 'config')
    op.add_column('financial_documents', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_financial_documents_organization_id'), 'financial_documents', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'financial_documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('sale_items', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sale_items_organization_id'), 'sale_items', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'sale_items', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('staff', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('staff_business_assignments', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_staff_business_assignments_organization_id'), 'staff_business_assignments', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'staff_business_assignments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_history', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_stock_history_organization_id'), 'stock_history', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'stock_history', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subscriptions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_constraint(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.alter_column('subscriptions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'stock_history', type_='foreignkey')
    op.drop_index(op.f('ix_stock_history_organization_id'), table_name='stock_history')
    op.drop_column('stock_history', 'organization_id')
    op.drop_constraint(None, 'staff_business_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_staff_business_assignments_organization_id'), table_name='staff_business_assignments')
    op.drop_column('staff_business_assignments', 'organization_id')
    op.alter_column('staff', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_column('sales', 'organization_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_organization_id'), table_name='sale_items')
    op.drop_column('sale_items', 'organization_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_column('payments', 'organization_id')
    op.drop_constraint(None, 'financial_documents', type_='foreignkey')
    op.drop_index(op.f('ix_financial_documents_organization_id'), table_name='financial_documents')
    op.drop_column('financial_documents', 'organization_id')
    op.add_column('businesses', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'settings')
    # ### end Alembic commands ###
