"""adds stocktake and stocktakeitem tables

Revision ID: 22c6061c963e
Revises: 2c15f343a2b1
Create Date: 2026-06-03 00:29:37.695737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22c6061c963e'
down_revision: Union[str, Sequence[str], None] = '2c15f343a2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_takes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', 'APPROVED', 'CANCELLED', name='stock_take_status_enum'), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_items_counted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_takes_business_id'), 'stock_takes', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_takes_id'), 'stock_takes', ['id'], unique=False)
    op.create_index(op.f('ix_stock_takes_performed_by'), 'stock_takes', ['performed_by'], unique=False)
    op.create_table('stock_take_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stock_take_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('system_stock', sa.Float(), nullable=False),
    sa.Column('counted_stock', sa.Float(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_take_id'], ['stock_takes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_take_items_id'), 'stock_take_items', ['id'], unique=False)
    op.create_index(op.f('ix_stock_take_items_product_id'), 'stock_take_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_take_items_stock_take_id'), 'stock_take_items', ['stock_take_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_take_items_stock_take_id'), table_name='stock_take_items')
    op.drop_index(op.f('ix_stock_take_items_product_id'), table_name='stock_take_items')
    op.drop_index(op.f('ix_stock_take_items_id'), table_name='stock_take_items')
    op.drop_table('stock_take_items')
    op.drop_index(op.f('ix_stock_takes_performed_by'), table_name='stock_takes')
    op.drop_index(op.f('ix_stock_takes_id'), table_name='stock_takes')
    op.drop_index(op.f('ix_stock_takes_business_id'), table_name='stock_takes')
    op.drop_table('stock_takes')
    # ### end Alembic commands ###
