"""refactors inventory_transaction table

Revision ID: 24b86def645d
Revises: 1f7523183204
Create Date: 2026-06-10 14:12:27.708706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b86def645d'
down_revision: Union[str, Sequence[str], None] = '1f7523183204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('inventory_transactions', 'movement_type',
               existing_type=postgresql.ENUM('PURCHASE', 'SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'STOCK_TAKE', 'RETURN', name='stock_movement_type_enum'),
               nullable=False)
    op.create_index(op.f('ix_inventory_transactions_movement_type'), 'inventory_transactions', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reason_code'), 'inventory_transactions', ['reason_code'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reference_type'), 'inventory_transactions', ['reference_type'], unique=False)
    op.drop_constraint(op.f('inventory_transactions_performed_by_fkey'), 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_transactions', 'staff', ['performed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_transactions_performed_by_fkey'), 'inventory_transactions', 'staff', ['performed_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_inventory_transactions_reference_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_reason_code'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_movement_type'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'movement_type',
               existing_type=postgresql.ENUM('PURCHASE', 'SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'STOCK_TAKE', 'RETURN', name='stock_movement_type_enum'),
               nullable=True)
    op.drop_column('inventory_transactions', 'notes')
    op.drop_column('inventory_transactions', 'reason_code')
    # ### end Alembic commands ###
