"""fixes some mappers

Revision ID: 28d03a220636
Revises: feea1f88e0fc
Create Date: 2026-06-23 18:59:48.673895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28d03a220636'
down_revision: Union[str, Sequence[str], None] = 'feea1f88e0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('stock_history', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_history', 'type')
    op.drop_column('businesses', 'tax_rate')
    # ### end Alembic commands ###
