"""removes assiged_at column from StaffAssignment table

Revision ID: 2c15f343a2b1
Revises: 82a6b5ff43ee
Create Date: 2026-06-02 20:33:10.668686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c15f343a2b1'
down_revision: Union[str, Sequence[str], None] = '82a6b5ff43ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_business_assignments', 'assigned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_business_assignments', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
