"""adds industry column to business model

Revision ID: 7d9f11b5a8fe
Revises: 1cd7948300ae
Create Date: 2026-08-13 23:58:44.109391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d9f11b5a8fe'
down_revision: Union[str, Sequence[str], None] = '1cd7948300ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('products', 'item_type',
               existing_type=postgresql.ENUM('PRODUCT', 'SERVICE', name='item_type_enum'),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'item_type',
               existing_type=postgresql.ENUM('PRODUCT', 'SERVICE', name='item_type_enum'),
               server_default=sa.text("'PRODUCT'::item_type_enum"),
               nullable=False)
    op.drop_column('businesses', 'industry')
    # ### end Alembic commands ###
