"""changed tenant tier to plan

Revision ID: 81b701305abc
Revises: 90095deddf03
Create Date: 2026-05-24 23:30:54.918733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81b701305abc'
down_revision: Union[str, Sequence[str], None] = '90095deddf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='sale_status_enum'),
               type_=sa.Enum('PENDING_PAYMENT', 'COMPLETED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', name='sale_status_enum'),
               existing_nullable=True)
    op.add_column('tenants', sa.Column('plan', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'TRIAL', name='tenant_tier_enum'), nullable=True))
    op.drop_column('tenants', 'tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tier', postgresql.ENUM('FREE', 'BRONZE', 'SILVER', 'GOLD', name='tenant_tier_enum'), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'plan')
    op.alter_column('sales', 'status',
               existing_type=sa.Enum('PENDING_PAYMENT', 'COMPLETED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', name='business_sale_status_enum'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='sale_status_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###
