"""added basemixin to staffassignment table

Revision ID: 82a6b5ff43ee
Revises: eef13f776c2d
Create Date: 2026-06-02 20:20:50.974428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82a6b5ff43ee'
down_revision: Union[str, Sequence[str], None] = 'eef13f776c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'quantity_refunded',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('staff_business_assignments', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('staff_business_assignments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('staff_business_assignments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('staff_business_assignments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_staff_business_assignments_id'), 'staff_business_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_business_assignments_id'), table_name='staff_business_assignments')
    op.drop_column('staff_business_assignments', 'deleted_at')
    op.drop_column('staff_business_assignments', 'updated_at')
    op.drop_column('staff_business_assignments', 'created_at')
    op.drop_column('staff_business_assignments', 'id')
    op.alter_column('sale_items', 'quantity_refunded',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
