"""removes sale_id from customers model

Revision ID: 845393ceec00
Revises: e8d7b41876de
Create Date: 2026-08-15 17:58:31.688317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '845393ceec00'
down_revision: Union[str, Sequence[str], None] = 'e8d7b41876de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_sale_id'), table_name='customers')
    op.drop_constraint(op.f('customers_sale_id_fkey'), 'customers', type_='foreignkey')
    op.drop_column('customers', 'sale_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('sale_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('customers_sale_id_fkey'), 'customers', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_customers_sale_id'), 'customers', ['sale_id'], unique=False)
    # ### end Alembic commands ###
