"""changed default subscription from free to trial and salestatus from completed to pending payment

Revision ID: 90095deddf03
Revises: 90d907a510f1
Create Date: 2026-05-24 23:14:16.836082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90095deddf03'
down_revision: Union[str, Sequence[str], None] = '90d907a510f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
