"""tawala v0.0.3 database schema design

Revision ID: 9c09b708861b
Revises: 701065b9011c
Create Date: 2026-05-28 02:01:59.483247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c09b708861b'
down_revision: Union[str, Sequence[str], None] = '701065b9011c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass