"""adds stockbatch table

Revision ID: ae466c892daa
Revises: 22c6061c963e
Create Date: 2026-06-03 02:32:58.764221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae466c892daa'
down_revision: Union[str, Sequence[str], None] = '22c6061c963e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_received', sa.Float(), nullable=False),
    sa.Column('quantity_remaining', sa.Float(), nullable=False),
    sa.Column('purchase_cost_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('received_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_batches_business_id'), 'stock_batches', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_id'), 'stock_batches', ['id'], unique=False)
    op.create_index(op.f('ix_stock_batches_product_id'), 'stock_batches', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_batches_product_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_business_id'), table_name='stock_batches')
    op.drop_table('stock_batches')
    # ### end Alembic commands ###
