"""adds discount and service fee columns

Revision ID: b003a8dc6013
Revises: 845393ceec00
Create Date: 2026-08-18 18:08:34.217138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b003a8dc6013'
down_revision: Union[str, Sequence[str], None] = '845393ceec00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('service_amount', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales', sa.Column('discount_amount', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount_amount')
    op.drop_column('sales', 'service_amount')
    # ### end Alembic commands ###
