"""touches a few tables

Revision ID: c7da504022e6
Revises: cf965515a8fd
Create Date: 2026-07-01 00:17:12.361166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7da504022e6'
down_revision: Union[str, Sequence[str], None] = 'cf965515a8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('popularity_score', sa.Float(), nullable=True))
    op.alter_column('subscriptions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'subscriptions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'max_businesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('max_businesses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.alter_column('subscriptions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('products', 'popularity_score')
    # ### end Alembic commands ###
