"""removes foreign key on business table to organizationC

Revision ID: cf965515a8fd
Revises: 24f8216687f5
Create Date: 2026-06-29 02:18:51.280818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf965515a8fd'
down_revision: Union[str, Sequence[str], None] = '24f8216687f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('businesses_organization_id_fkey'), 'businesses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('businesses_organization_id_fkey'), 'businesses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
