"""adds a sale id to customer model, this points back to the sale

Revision ID: e8d7b41876de
Revises: 7d9f11b5a8fe
Create Date: 2026-08-15 16:59:44.074368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8d7b41876de'
down_revision: Union[str, Sequence[str], None] = '7d9f11b5a8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('sale_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_customers_sale_id'), 'customers', ['sale_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_sale_id'), table_name='customers')
    op.drop_column('customers', 'sale_id')
    # ### end Alembic commands ###
