"""changed InventoryTransaction table to StockHistory

Revision ID: efc23adf3440
Revises: 24b86def645d
Create Date: 2026-06-14 01:45:12.286255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc23adf3440'
down_revision: Union[str, Sequence[str], None] = '24b86def645d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT', 'STOCK_TAKE', name='stock_history_type_enum'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('previous_stock', sa.Float(), nullable=True),
    sa.Column('new_stock', sa.Float(), nullable=False),
    sa.Column('buying_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_history_business_id'), 'stock_history', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_history_id'), 'stock_history', ['id'], unique=False)
    op.create_index(op.f('ix_stock_history_movement_type'), 'stock_history', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_history_performed_by'), 'stock_history', ['performed_by'], unique=False)
    op.create_index(op.f('ix_stock_history_product_id'), 'stock_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_history_reason_code'), 'stock_history', ['reason_code'], unique=False)
    op.create_index(op.f('ix_stock_history_reference_id'), 'stock_history', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_history_reference_type'), 'stock_history', ['reference_type'], unique=False)
    op.drop_index(op.f('ix_inventory_transactions_business_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_movement_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_performed_by'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_reason_code'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_reference_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_reference_type'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('movement_type', postgresql.ENUM('PURCHASE', 'SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'STOCK_TAKE', 'RETURN', name='stock_movement_type_enum'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('previous_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('new_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('buying_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('inventory_transactions_business_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['staff.id'], name=op.f('inventory_transactions_performed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('inventory_transactions_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_transactions_pkey'))
    )
    op.create_index(op.f('ix_inventory_transactions_reference_type'), 'inventory_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reference_id'), 'inventory_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reason_code'), 'inventory_transactions', ['reason_code'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_performed_by'), 'inventory_transactions', ['performed_by'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_movement_type'), 'inventory_transactions', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_business_id'), 'inventory_transactions', ['business_id'], unique=False)
    op.drop_index(op.f('ix_stock_history_reference_type'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_reference_id'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_reason_code'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_product_id'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_performed_by'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_movement_type'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_id'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_business_id'), table_name='stock_history')
    op.drop_table('stock_history')
    # ### end Alembic commands ###
