"""safe evolution of organization and new features

Revision ID: f827c4e67f78
Revises: 9c09b708861b
Create Date: 2026-05-28 02:38:24.902930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f827c4e67f78'
down_revision: Union[str, Sequence[str], None] = '9c09b708861b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_active'), 'organizations', ['active'], unique=False)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_organization_id'), 'organizations', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'STOCK_TAKE', 'RETURN', name='stock_movement_type_enum'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('previous_stock', sa.Float(), nullable=False),
    sa.Column('new_stock', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_business_id'), 'inventory_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reference_id'), 'inventory_transactions', ['reference_id'], unique=False)
    op.create_table('mpesa_payloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mpesa_receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_payloads_id'), 'mpesa_payloads', ['id'], unique=False)
    op.create_index(op.f('ix_mpesa_payloads_mpesa_receipt_number'), 'mpesa_payloads', ['mpesa_receipt_number'], unique=False)
    op.create_index(op.f('ix_mpesa_payloads_payment_id'), 'mpesa_payloads', ['payment_id'], unique=False)
    op.create_index(op.f('ix_mpesa_payloads_transaction_type'), 'mpesa_payloads', ['transaction_type'], unique=False)
    op.add_column('businesses', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('businesses', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('businesses', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_organization_id'), 'businesses', ['organization_id'], unique=False)
    op.add_column('products', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('min_stock_level', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('last_stock_take', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.add_column('sales', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    op.add_column('staff', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('staff', sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staff', sa.Column('pin_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staff', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_staff_organization_id'), 'staff', ['organization_id'], unique=False)
    op.add_column('subscriptions', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_businesses', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.drop_column('subscriptions', 'max_registers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('max_registers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'max_businesses')
    op.drop_column('subscriptions', 'organization_id')
    op.drop_index(op.f('ix_staff_organization_id'), table_name='staff')
    op.drop_column('staff', 'phone')
    op.drop_column('staff', 'pin_salt')
    op.drop_column('staff', 'pin_hash')
    op.drop_column('staff', 'organization_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'customer_id')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_column('products', 'last_stock_take')
    op.drop_column('products', 'min_stock_level')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'organization_id')
    op.drop_column('products', 'tenant_id')
    op.drop_index(op.f('ix_businesses_organization_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=True)
    op.drop_column('businesses', 'phone')
    op.drop_column('businesses', 'address')
    op.drop_column('businesses', 'organization_id')
    op.drop_index(op.f('ix_mpesa_payloads_transaction_type'), table_name='mpesa_payloads')
    op.drop_index(op.f('ix_mpesa_payloads_payment_id'), table_name='mpesa_payloads')
    op.drop_index(op.f('ix_mpesa_payloads_mpesa_receipt_number'), table_name='mpesa_payloads')
    op.drop_index(op.f('ix_mpesa_payloads_id'), table_name='mpesa_payloads')
    op.drop_table('mpesa_payloads')
    op.drop_index(op.f('ix_inventory_transactions_reference_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_business_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_organizations_organization_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
