"""database schema design

Revision ID: fb80521d3103
Revises: 18cc7093f908
Create Date: 2026-06-05 02:58:24.426307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb80521d3103'
down_revision: Union[str, Sequence[str], None] = '18cc7093f908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_takes_business_id'), table_name='stock_takes')
    op.drop_index(op.f('ix_stock_takes_id'), table_name='stock_takes')
    op.drop_index(op.f('ix_stock_takes_performed_by'), table_name='stock_takes')
    # op.drop_table('stock_takes')
    op.execute("DROP TABLE IF EXISTS stock_take CASCADE")
    op.drop_index(op.f('ix_stock_batches_business_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_product_id'), table_name='stock_batches')
    # op.drop_table('stock_batches')
    op.execute("DROP TABLE IF EXISTS stock_batches CASCADE")
    op.drop_index(op.f('ix_stock_take_items_id'), table_name='stock_take_items')
    op.drop_index(op.f('ix_stock_take_items_product_id'), table_name='stock_take_items')
    op.drop_index(op.f('ix_stock_take_items_stock_take_id'), table_name='stock_take_items')
    # op.drop_table('stock_take_items')
    op.execute("DROP TABLE IF EXISTS stock_take_items CASCADE")
    op.drop_constraint(op.f('customers_business_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('inventory_transactions', sa.Column('purchase_cost_price', sa.Float(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('batch_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_inventory_transactions_performed_by'), 'inventory_transactions', ['performed_by'], unique=False)
    op.drop_constraint(op.f('inventory_transactions_business_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(op.f('inventory_transactions_product_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(op.f('inventory_transactions_performed_by_fkey'), 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_transactions', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inventory_transactions', 'staff', ['performed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_transactions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organizations_organization_id'), table_name='organizations')
    op.drop_column('organizations', 'organization_id')
    op.drop_constraint(op.f('payments_sale_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_business_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_business_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sale_items_sale_id_fkey'), 'sale_items', type_='foreignkey')
    # op.drop_constraint(op.f('sale_items_stock_batch_id_fkey'), 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sale_items', 'stock_batch_id')
    op.drop_constraint(op.f('sales_business_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_subscriptions_end_date'), table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscriptions_end_date'), 'subscriptions', ['end_date'], unique=False)
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_business_id_fkey'), 'sales', 'businesses', ['business_id'], ['id'])
    op.add_column('sale_items', sa.Column('stock_batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    # op.create_foreign_key(op.f('sale_items_stock_batch_id_fkey'), 'sale_items', 'stock_batches', ['stock_batch_id'], ['id'])
    op.create_foreign_key(op.f('sale_items_sale_id_fkey'), 'sale_items', 'sales', ['sale_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_business_id_fkey'), 'products', 'businesses', ['business_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_business_id_fkey'), 'payments', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(op.f('payments_sale_id_fkey'), 'payments', 'sales', ['sale_id'], ['id'])
    op.add_column('organizations', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_organizations_organization_id'), 'organizations', ['organization_id'], unique=False)
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_transactions_performed_by_fkey'), 'inventory_transactions', 'staff', ['performed_by'], ['id'])
    op.create_foreign_key(op.f('inventory_transactions_product_id_fkey'), 'inventory_transactions', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('inventory_transactions_business_id_fkey'), 'inventory_transactions', 'businesses', ['business_id'], ['id'])
    op.drop_index(op.f('ix_inventory_transactions_performed_by'), table_name='inventory_transactions')
    op.drop_column('inventory_transactions', 'batch_reference')
    op.drop_column('inventory_transactions', 'selling_price')
    op.drop_column('inventory_transactions', 'purchase_cost_price')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_business_id_fkey'), 'customers', 'businesses', ['business_id'], ['id'])
    op.create_table('stock_take_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('stock_take_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('system_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('counted_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('difference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_take_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['stock_take_id'], ['stock_takes.id'], name=op.f('stock_take_items_stock_take_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_take_items_pkey'))
    )
    op.create_index(op.f('ix_stock_take_items_stock_take_id'), 'stock_take_items', ['stock_take_id'], unique=False)
    op.create_index(op.f('ix_stock_take_items_product_id'), 'stock_take_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_take_items_id'), 'stock_take_items', ['id'], unique=False)
    op.create_table('stock_batches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity_received', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity_remaining', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('purchase_cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('batch_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('received_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('stock_batches_business_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_batches_product_id_fkey')),
    sa.ForeignKeyConstraint(['received_by'], ['staff.id'], name=op.f('stock_batches_received_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_batches_pkey'))
    )
    op.create_index(op.f('ix_stock_batches_product_id'), 'stock_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_id'), 'stock_batches', ['id'], unique=False)
    op.create_index(op.f('ix_stock_batches_business_id'), 'stock_batches', ['business_id'], unique=False)
    op.create_table('stock_takes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'COMPLETED', 'APPROVED', 'CANCELLED', name='stock_take_status_enum'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_items_counted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('stock_takes_business_id_fkey')),
    sa.ForeignKeyConstraint(['performed_by'], ['staff.id'], name=op.f('stock_takes_performed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_takes_pkey'))
    )
    op.create_index(op.f('ix_stock_takes_performed_by'), 'stock_takes', ['performed_by'], unique=False)
    op.create_index(op.f('ix_stock_takes_id'), 'stock_takes', ['id'], unique=False)
    op.create_index(op.f('ix_stock_takes_business_id'), 'stock_takes', ['business_id'], unique=False)
    # ### end Alembic commands ###
