"""adds_receipt_and_invoices_tables

Revision ID: feea1f88e0fc
Revises: b9cfbb883575
Create Date: 2026-06-18 18:13:40.464627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feea1f88e0fc'
down_revision: Union[str, Sequence[str], None] = 'b9cfbb883575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.Enum('INVOICE', 'RECEIPT', 'CREDIT_NOTE', name='documenttype'), nullable=False),
    sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('fiscal_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_documents_business_id'), 'financial_documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_financial_documents_customer_id'), 'financial_documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_financial_documents_document_number'), 'financial_documents', ['document_number'], unique=True)
    op.create_index(op.f('ix_financial_documents_document_type'), 'financial_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_financial_documents_id'), 'financial_documents', ['id'], unique=False)
    op.create_index(op.f('ix_financial_documents_sale_id'), 'financial_documents', ['sale_id'], unique=True)
    op.drop_index(op.f('ix_mpesa_payloads_id'), table_name='mpesa_payloads')
    op.drop_index(op.f('ix_mpesa_payloads_mpesa_receipt_number'), table_name='mpesa_payloads')
    op.drop_index(op.f('ix_mpesa_payloads_payment_id'), table_name='mpesa_payloads')
    op.drop_index(op.f('ix_mpesa_payloads_transaction_type'), table_name='mpesa_payloads')
    op.drop_table('mpesa_payloads')
    op.drop_index(op.f('ix_sale_ledger_events_id'), table_name='sale_ledger_events')
    op.drop_index(op.f('ix_sale_ledger_events_product_id_context'), table_name='sale_ledger_events')
    op.drop_index(op.f('ix_sale_ledger_events_sale_id'), table_name='sale_ledger_events')
    op.drop_table('sale_ledger_events')
    op.create_foreign_key(None, 'businesses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('customers', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('customers_organization_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sales', 'status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'COMPLETED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', name='business_sale_status_enum'),
               nullable=False)
    op.add_column('staff_business_assignments', sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'CASHIER', 'ADMIN', name='staff_role_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_business_assignments', 'role')
    op.alter_column('sales', 'status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'COMPLETED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', name='business_sale_status_enum'),
               nullable=True)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_organization_id_fkey'), 'customers', 'organizations', ['organization_id'], ['id'])
    op.alter_column('customers', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.create_table('sale_ledger_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sale_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('INITIAL_SALE', 'INVOICE_ISSUED', 'PAYMENT_COLLECTED', 'ITEM_RETURNED', 'DISPUTE_RAISED', name='event_type_enum'), autoincrement=False, nullable=True),
    sa.Column('amount_delta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('product_id_context', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('sale_ledger_events_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_ledger_events_pkey'))
    )
    op.create_index(op.f('ix_sale_ledger_events_sale_id'), 'sale_ledger_events', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_ledger_events_product_id_context'), 'sale_ledger_events', ['product_id_context'], unique=False)
    op.create_index(op.f('ix_sale_ledger_events_id'), 'sale_ledger_events', ['id'], unique=False)
    op.create_table('mpesa_payloads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_reconciled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reconciled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('mpesa_payloads_payment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mpesa_payloads_pkey'))
    )
    op.create_index(op.f('ix_mpesa_payloads_transaction_type'), 'mpesa_payloads', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_mpesa_payloads_payment_id'), 'mpesa_payloads', ['payment_id'], unique=False)
    op.create_index(op.f('ix_mpesa_payloads_mpesa_receipt_number'), 'mpesa_payloads', ['mpesa_receipt_number'], unique=False)
    op.create_index(op.f('ix_mpesa_payloads_id'), 'mpesa_payloads', ['id'], unique=False)
    op.drop_index(op.f('ix_financial_documents_sale_id'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_id'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_document_type'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_document_number'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_customer_id'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_business_id'), table_name='financial_documents')
    op.drop_table('financial_documents')
    # ### end Alembic commands ###
