"""changed stockhistory movementType column to somethimg sqlmodel can manage

Revision ID: ffed9fe9e517
Revises: 1cce4dfdaafe
Create Date: 2026-06-24 00:57:14.697361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffed9fe9e517'
down_revision: Union[str, Sequence[str], None] = '1cce4dfdaafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
